apiVersion: v1
kind: Secret
metadata:
  name: jenkins-agent-secret
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/service-account.name: jenkins-agent-account
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-agent-account
  namespace: ${NAMESPACE}
secrets:
- name: jenkins-agent-secret
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-role-binding
  namespace: ${NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: jenkins-agent-account
  namespace: ${NAMESPACE}