apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${CONTAINER}
  name: ${CONTAINER}-service
  namespace: ${NAMESPACE}
spec:
  clusterIP: 
  ports:
    - name: admin-tcp
      port: 56565
      protocol: TCP
      targetPort: 5555
    - name: websocket-tcp
      port: 51333
      protocol: TCP
      targetPort: 5333
  selector:
    deploymentconfig: ${CONTAINER}
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Route
metadata:
  name: ${CONTAINER}-route
  namespace: ${NAMESPACE}
spec:
  host: ${CONTAINER}.193-26-203-31.nip.io
  port:
    targetPort: admin-tcp
  to:
    kind: Service
    name: ${CONTAINER}-service
    weight: 100
  wildcardPolicy: None
