apiVersion: v1
kind: ConfigMap
metadata:
  name: license
data:
  license.xml: |
      <?xml version="1.0" encoding="US-ASCII"?>
      <SoftwareAG_License>
      <Component Id="SalesInfo">
      <SerialNumber>0000490163</SerialNumber>
      <LicenseKey>096FFDE9B3A9F000C33D6FFE662E88F1</LicenseKey>
      <CustomerID>3150000</CustomerID>
      <CustomerName>Software AG for Solution Book Internal USE ONLY</CustomerName>
      <ContractDetails>SOFTWARE AG internal license solely for sales promotion and internal training purposes. Please note that this access key is for your personal use only. Access and software shall not be forwarded to anybody else</ContractDetails>
      <ContractPosNumber>10</ContractPosNumber>
      <LicenseTypeDetails>Internal</LicenseTypeDetails>
      <AutoCallHome>No</AutoCallHome>
      </Component>
      <Component Id="ProductInfo">
      <ExpirationDate>2020/10/31</ExpirationDate>
      <OS>win, Linux</OS>
      <ProductCode>TDBFX</ProductCode>
      <ProductName>Terracotta</ProductName>
      <ProductVersion>10.1</ProductVersion>
      <Usage/>
      <RenewalDate/>
      <HigherLevPosNr/>
      <HigherLevProdCode/>
      <HigherLevProdName/>
      </Component>
      <Component Id="LicenseInfo">
      <PriceUnit>GBS</PriceUnit>
      <PriceQuantity>100</PriceQuantity>
      <TypeOfInstallation/>
      <LicenseType/>
      <ExtendedRights/>
      <LicenseVersion>1.2</LicenseVersion>
      <Metering>MNO</Metering>
      </Component>
      <Component Id="Terracotta">
      <ProductCode>TDB</ProductCode>
      <ProductVersion>10.1</ProductVersion>
      <Caching>yes</Caching>
      <TMC>yes</TMC>
      <MultiStripe>yes</MultiStripe>
      <Security>yes</Security>
      <TCStore>yes</TCStore>
      <SearchCompute>yes</SearchCompute>
      <Websessions>no</Websessions>
      </Component>
      </SoftwareAG_License>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tc-config
data:
  tc-config.xml: |
      <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
      <!--
        Copyright (c) 2011-2018 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
        Use, reproduction, transfer, publication or disclosure is prohibited except as specifically provided for in your License Agreement with Software AG.
        -->
      <tc-config xmlns="http://www.terracotta.org/config">
        <plugins>
          <config>
            <ohr:offheap-resources xmlns:backup="http://www.terracottatech.com/config/backup-restore" xmlns:data="http://www.terracottatech.com/config/data-roots" xmlns:ohr="http://www.terracotta.org/config/offheap-resource" xmlns:lease="http://www.terracotta.org/service/lease">
              <ohr:resource name="offheap-1" unit="MB">256</ohr:resource>
            </ohr:offheap-resources>
          </config>
          <config>
            <data:data-directories xmlns:backup="http://www.terracottatech.com/config/backup-restore" xmlns:data="http://www.terracottatech.com/config/data-roots" xmlns:ohr="http://www.terracotta.org/config/offheap-resource" xmlns:lease="http://www.terracotta.org/service/lease">
              <data:directory name="PLATFORM" use-for-platform="true">/data/dataroots/platform</data:directory>
              <data:directory name="dataroot-1" use-for-platform="false">/data/dataroots/dataroot-1</data:directory>
            </data:data-directories>
          </config>
          <service>
            <backup:backup-restore xmlns:backup="http://www.terracottatech.com/config/backup-restore" xmlns:data="http://www.terracottatech.com/config/data-roots" xmlns:ohr="http://www.terracotta.org/config/offheap-resource" xmlns:lease="http://www.terracotta.org/service/lease">
              <backup:backup-location path="/data/backups"/>
            </backup:backup-restore>
          </service>
        </plugins>
        <servers>
          <server host="terracotta.api-hip-workshop" name="terracotta-0" bind="0.0.0.0">
            <logs>/opt/softwareag/terracotta/server/conf/stdout:</logs>
            <tsa-port bind="0.0.0.0">9410</tsa-port>
            <tsa-group-port bind="0.0.0.0">9430</tsa-group-port>
          </server>
          <client-reconnect-window>120</client-reconnect-window>
        </servers>
      </tc-config>
---
apiVersion: v1
kind: Service
metadata:
  name: terracotta
  labels:
    service: terracotta
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  ports:
    - name: 9410-tcp
      port: 9410
    - name: 9430-tcp
      port: 9430
  selector:
    name: terracotta
  sessionAffinity: None
  type: ClusterIP
---
kind: "StatefulSet"
apiVersion: "apps/v1"
metadata:
  name: "terracotta"
  labels:
    name: "terracotta"
spec:
  selector:
    matchLabels:
      name: "terracotta"
  serviceName: terracotta
  template:
    metadata:
      labels:
        name: "terracotta"
    spec:
      containers:
      - name: "terracotta"
        env:
          - name: ACCEPT_EULA
            value: 'Y'
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        command: ["bin/start-tc-server.sh"]
        args: ["-f", "/config/tc-config.xml", "-n", "$(POD_NAME)"]
        image: "172.30.1.1:5000/api-hip-workshop/terracotta-server:10.5"
        ports:
          - containerPort: 9410
            name: terracotta-port
          - containerPort: 9430
            name: sync-port
        volumeMounts:
          - name: config-volume
            mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: tc-config
  replicas: 1
  triggers:
    - type: "ConfigChange"
  strategy:
    type: "Rolling"
  paused: false
  revisionHistoryLimit: 2
  minReadySeconds: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-tool
spec:
  template:
    metadata:
      name: cluster-tool
    spec:
      containers:
      - name: cluster-tool
        image: store/softwareag/terracotta-cluster-tool:10.3
        imagePullPolicy: Always #ensure the node will always try to pull from the registry
        args: ["configure", "-n", "DemoCluster", "/config/tc-config.xml", "-l", "/licenses/license.xml"]
        env:
        - name: ACCEPT_EULA
          value: "Y"
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: license-volume
          mountPath: /licenses
      volumes:
      - name: config-volume
        configMap:
          name: tc-config
      - name: license-volume
        configMap:
          name: license
      restartPolicy: OnFailure
